opt_in_rules:
  - implicit_return
  - let_var_whitespace
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - unused_import
