name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9.0"
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-Migration-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-Migration
      - name: Build
        run: swift build
      - name: Test
        run: swift test
